### PR TITLE
Remove deprecations

### PR DESCRIPTION
**Pull request by gmalette**
This removes deprecations for Rails 5. 
I have no idea how to run the tests. 

I manually tested and everything seems to still work

### CODE REVIEW

**Comment by gmalette** [comment]
@sgnr

**Comment by gmalette** [comment]
@kirs @rafaelfranca if y'all can help me out, it would be awesome

**Comment by lastgabs** [comment]
@Shopify/rails5

**Comment by in-the-mood-for-mov** [comment]
Why isn't this the default in Rails?

**Comment by rafaelfranca** [comment]
hmm, in Rails 5 I think you don't need it. You can use bigint in the migration and also you can configure the generator to use bigint. The only thing that may be missing is using `limit: 8` in references.

**Comment by gmalette** [comment]
> you can configure the generator to use bigint

OH! How can we do that? The purpose of this gem is that we don't manually have to specify `bigint` because people don't think about it when doing `t.references :other_model`. If there's a way to configure the generator to always use it, that'd be even better

**Comment by rafaelfranca** [comment]
```
config.generators do |g|
  g.orm :active_record, primary_key_type: :bigserial
end
```

We may add a new option to references too:

```
config.generators do |g|
  g.orm :active_record, primary_key_type: :bigserial, references_type: :bigint
end
```

**Comment by gmalette** [comment]
So `references` aren't handled yet? Why are the two config required? Sounds like any FK would need to be the same type as the PK

**Comment by rafaelfranca** [comment]
yeah, it is not handled yet, and agree we don't need a new config. we can change the migration template easily to use the same value in both places.

**Comment by swalkinshaw** [comment]
Can we still get this merged in the meantime?

One thing of note: the usage of `prepend` now requires Ruby 2.0+. Not a huge deal and we've done it with other gems like shopify_app and shopify_api.

We could set `required_ruby_version` in the gemspec.

**Comment by gmalette** [comment]
@swalkinshaw the only problem I have with this is I haven't been able to run tests

**Comment by swalkinshaw** [comment]
I tried to give it a shot as well... and the results were not good 💀 

Looks like this test suite is extremely brittle (and maybe just broken).

**Comment by gmalette** [comment]
Yeah I think it would need to be rewritten for Rails 5, but if this is a feature or Rails 5 it's not worth the investment. Can you manually 🎩 then I'll merge

**Comment by swalkinshaw** [comment]
🎩  worked for me

**Pull request merged**
